name: Build Mod

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin

      - name: Generate gradlew
        run: |
          gradle wrapper --gradle-version 4.9

      - name: Setup Forge workspace
        run: ./gradlew setupDecompWorkspace

      - name: Build mod
        run: ./gradlew build

      - name: Upload JAR
        uses: actions/upload-artifact@v4
        with:
          name: JumpResetMod1.2
          path: build/libs/*.jar
